### ISSUE TITLE
Digikam fails to start on image of 7.4.0

### ISSUE THREAD

**Issue by AlmightyFrog** [linuxserver/docker-digikam#14]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Running image 7.3.0 works without issues, but at 7.4.0 it does not start with "fuse: device not found" error.
------------------------------

## Expected Behavior
Using image of 7.4.0 should be able to start digikam.

## Current Behavior
Digikam does not start. If you run it in terminal you get an error "fuse: device not found, try 'modprobe fuse' first" like shown in following
![grafik](https://user-images.githubusercontent.com/2421469/146660205-f0afb79a-4b7e-450f-942e-e04932da4986.png)
You can switch back to 7.3.0 and have that running without any issue btw.

## Steps to Reproduce

1. Start 7.4.0 docker image
2. Open Terminal
3. Start /app/digikam

## Environment
**OS:** arch linux
**CPU architecture:** x86_64
**How docker service was installed:** distro repo

**Comment by Roxedus** [comment]
Please fill the missing info from the template.

**Comment by drizuid** [comment]
OP was too lazy to fill the template out, but we received 2 more reports today and i personally tested:

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]





------------------------------

## Expected Behavior
Screen should show the application

## Current Behavior
screen is black and offers no functionality

## Steps to Reproduce
1. Run the container
2. access the application per application setup
3. patiently wait for black screen to change into app screen

## Environment
Debian 11
x86_64
official docker repo - `Docker version 20.10.12, build e91ed57`

## Command used to create docker container (run/create/compose/screenshot)
docker run -d --rm --name=digikam -e PUID=1006 -e PGID=996 -e TZ=America/New_York -p 3001:3000 -v /tmp/digikam:/config lscr.io/linuxserver/digikam

## Docker logs
https://0bin.net/paste/Xr5covMD#TVB2N6l6g5GaWkhLYXKW-163sciVekiSfCkzzMPK/Xf

**Comment by drizuid** [comment]
for now, anyone facing this issue can use lspipepr/digikam:7.4.0-pkg-5ac69862-pr-15 which SHOULD resolve the issue. Let us know if it does not.
