### ISSUE TITLE
Startup fails: Failed to close file descriptor for child process (Operation not permitted)

### ISSUE THREAD

**Issue by bosswaz** [linuxserver/docker-digikam#22]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]
Had digikam working beautifully in docker unraid.
Then went headless and rebooted (not sure if this is red herring or not).
Now after serval attempts to re-install (and killing appdata) the startup will not run (error in title).
Where can I find help with this issue?

Could it be database related?

------------------------------

## Steps to Reproduce

1.
2.
3.
4.

## Environment
**OS:**
**CPU architecture:** x86_64/arm32/arm64
**How docker service was installed:**

**Comment by bosswaz** [comment]
Here is the Digikam log:

rdpkeybControl: what 1
rdpkeybDeviceOn:
rdpDeferredRandR:
rdpResizeSession: width 1024 height 768
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1024 height 768 mmWidth 271 mmHeight 203
rdpRRGetInfo:
  screen resized to 1024x768
  RRScreenSizeSet ok 1
rdpResizeSession: width 1920 height 975
  calling RRScreenSizeSet
rdpRRScreenSetSize: width 1920 height 975 mmWidth 508 mmHeight 258
rdpRRGetInfo:
  screen resized to 1920x975
  RRScreenSizeSet ok 1
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 7
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x556493074a70
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1920 height 975 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 1 shmemptr 0x15330e182000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1920 cy 975
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
(EE) Failed to open authorization file ".Xauthority": No such file or directory
rdpRRGetInfo:
rdpClientConProcessMsgClientInfo:
  got client info bytes 7072
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1920 height 975
rdpLoadLayout: keylayout 0x00000409 variant  display 11
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
guacd[565]: INFO:       Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[565]: INFO:       Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[565]: INFO:       Connected to RDPDR 1.12 as client 0xe5368604
fuse: device not found, try 'modprobe fuse' first
guacd[565]: INFO:       RDPDR user logged on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[565]: INFO:       User "@f24389eb-07ee-4258-b7eb-b5a0854696bb" disconnected (0 users remain)
guacd[565]: INFO:       Last user of connection "$cd549161-be86-42cc-9d20-6a201cb99834" disconnected
[2022-03-18 09:55:11] [Connection 2]  Closing connection with error:  Error: not opened
    at WebSocket.send (/gclient/node_modules/ws/lib/WebSocket.js:218:38)
    at ClientConnection.send (/gclient/node_modules/guacamole-lite/lib/ClientConnection.js:125:24)
    at GuacdClient.sendBufferToWebSocket (/gclient/node_modules/guacamole-lite/lib/GuacdClient.js:172:35)
    at GuacdClient.processReceivedData (/gclient/node_modules/guacamole-lite/lib/GuacdClient.js:163:14)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Socket.Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
[2022-03-18 09:55:11] [Connection 2]  Closing guacd connection
[2022-03-18 09:55:11] [Connection 2]  Client connection closed
guacd[565]: INFO:       Internal RDP client disconnected
guacd[412]: INFO:       Connection "$cd549161-be86-42cc-9d20-6a201cb99834" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x556493074a70
Closing all connections and exiting...

**Comment by andreascschmidt** [comment]
May I ask why this issue was marked as invalid? 
I have the same error since maybe 2 or 3 digicam versions.

**Comment by j0nnymoe** [comment]
Because the original poster ignored the issue template when they opened it.

**Comment by bosswaz** [comment]
Yes I'm guilty...sorry about not following templates...I'm a first time
poster...my digikam is still down...too bad...it was filling my
needs...perhaps I can take another shot logging this issue...

**Comment by andreascschmidt** [comment]
can you reopen please, so we have the full trail?

here we go

**Expected Behaviour**
digikam starts and I can login using the xorg web UI

**Current Behaviour**
WebUI starts, but the application is not starting.
Error on the screen 
![image](https://user-images.githubusercontent.com/11931192/161391027-28d08811-ab38-4ce4-bd2b-c07878f6f0c4.png)

**Steps to Reproduce**
install  build_version | Linuxserver.io version:- 7.6.0-ls70 Build-date:- 2022-03-31T15:06:49+02:00
(I use a Qnap kx86 but had the same result on plain Ubuntu 22.04)
launch browser and go to http://IPadress:3000

**Environment**
not sure what to put into here 

**OS:**
CPU architecture: x86_64

**How docker service was installed:**
apt install docker.io Ubuntu
build in container station on Qnap
portainer to manage and monitor

**Command used to create docker container (run/create/compose/screenshot)**
version: "2.2"
services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /share/homes/andreas/digikam/config:/config:rw
      - /share/CACHEDEV3_DATA/Backups/!BT-SYNC_Directorires/Dropbox/:/photos:rw
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
#    mem_limit: 1500M
    mem_limit: 4000M
#    mem_reservation: 256M
    cpu_percent: 50
    cpus: 1
    cpu_shares: 50

version: "2.2"
services:
  digikam:
    image: ghcr.io/linuxserver/digikam
    container_name: digikam
#    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /share/homes/andreas/digikam/config:/config:rw
      - /share/CACHEDEV3_DATA/Backups/!BT-SYNC_Directorires/Dropbox/:/photos:rw
    ports:
      - 3000:3000 #optional
    restart: unless-stopped
#    mem_limit: 1500M
    mem_limit: 4000M
#    mem_reservation: 256M
    cpu_percent: 50
    cpus: 1
    cpu_shares: 50


**Docker logs**
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 0 numOutputs 0 monitorCount 0
rdpRRSetRdpOutputs: add output 0 left 0 top 0 width 1824 height 988
rdpLoadLayout: keylayout 0x00000409 variant  display 11
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[557]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[557]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[557]: INFO:	Connected to RDPDR 1.12 as client 0x1c4768ea
guacd[557]: INFO:	RDPDR user logged on
[2022-04-02 08:27:09] [Connection 1]  Closing connection with error:  1006
[2022-04-02 08:27:09] [Connection 1]  Closing guacd connection
[2022-04-02 08:27:09] [Connection 1]  Client connection closed
guacd[557]: ERROR:	User is not responding.
guacd[557]: INFO:	User "@7a85887d-ed19-4e0f-9b90-881a07fe9d9f" disconnected (0 users remain)
guacd[557]: INFO:	Last user of connection "$8fb8b5f1-5f78-4128-bc83-c7d9cf02c7db" disconnected
guacd[557]: INFO:	Internal RDP client disconnected
guacd[405]: INFO:	Connection "$8fb8b5f1-5f78-4128-bc83-c7d9cf02c7db" removed.
rdpClientConRecv: g_sck_recv failed(returned 0)
rdpClientConRecvMsg: error
rdpClientConCheck: rdpClientConGotData failed
rdpClientConDisconnect:
rdpRemoveClientConFromDev: removing clientCon 0x55777415c950
[2022-04-02 17:01:31] [Connection 2]  Client connection open
[2022-04-02 17:01:31] [Connection 2]  Opening guacd connection
[2022-04-02 17:01:31] [Connection 2]  guacd connection open
[2022-04-02 17:01:31] [Connection 2]  Selecting connection type: rdp
[2022-04-02 17:01:31] [Connection 2]  Sending opCode: 6.select,3.rdp;
guacd[405]: INFO:	Creating new client for protocol "rdp"
guacd[405]: INFO:	Connection ID is "$8f6fe7cb-01eb-4326-aa7d-35373f39e916"
[2022-04-02 17:01:35] [Connection 2]  Sending opCode: 4.size,4.1827,13.988?undefined,2.96;
[2022-04-02 17:01:35] [Connection 2]  Sending opCode: 5.audio,9.audio/L16;
[2022-04-02 17:01:35] [Connection 2]  Sending opCode: 5.video;
[2022-04-02 17:01:35] [Connection 2]  Sending opCode: 5.image;
[2022-04-02 17:01:35] [Connection 2]  Server sent handshake: 4.args,13.VERSION_1_1_0,8.hostname,4.port,6.domain,8.username,8.password,5.width,6.height,3.dpi,15.initial-program,11.color-depth,13.disable-audio,15.enable-printing,12.printer-name,12.enable-drive,10.drive-name,10.drive-path,17.create-drive-path,7.console,13.console-audio,13.server-layout,8.security,11.ignore-cert,12.disable-auth,10.remote-app,14.remote-app-dir,15.remote-app-args,15.static-channels,11.client-name,16.enable-wallpaper,14.enable-theming,21.enable-font-smoothing,23.enable-full-window-drag,26.enable-desktop-composition,22.enable-menu-animations,22.disable-bitmap-caching,25.disable-offscreen-caching,21.disable-glyph-caching,16.preconnection-id,18.preconnection-blob,8.timezone,14.recording-path,14.recording-name,24.recording-exclude-output,23.recording-exclude-mouse,22.recording-include-keys,21.create-recording-path,13.resize-method,18.enable-audio-input,9.read-only,16.gateway-hostname,12.gateway-port,14.gateway-domain,16.gateway-username,16.gateway-password,17.load-balance-info
[2022-04-02 17:01:35] [Connection 2]  Sending opCode: 7.connect,0.,9.127.0.0.1,4.3389,0.,3.abc,3.abc,4.1827,13.988?undefined,2.96,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,12.en-us-qwerty,3.any,4.true,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.,0.;
guacd[617]: INFO:	Security mode: Negotiate (ANY)
guacd[617]: INFO:	Resize method: none
guacd[617]: INFO:	User "@f0c5c865-6782-4795-8c8f-de8e14a24010" joined connection "$8f6fe7cb-01eb-4326-aa7d-35373f39e916" (1 users now present)
guacd[617]: INFO:	Loading keymap "base"
guacd[617]: INFO:	Loading keymap "en-us-qwerty"
rdpClientConGotConnection:
rdpClientConGotConnection: g_sck_accept ok new_sck 7
rdpClientConGetConnection: idle_disconnect_timeout set to non-positive value, idle timer turned off
rdpAddClientConToDev: adding first clientCon 0x55777415c950
rdpClientConProcessMsgVersion: version 0 0 0 1
rdpClientConProcessScreenSizeMsg: set width 1824 height 988 bpp 16
rdpClientConProcessScreenSizeMsg: shmemid 1 shmemptr 0x7f2a669e8000
rdpClientConProcessMsgClientInput: invalidate x 0 y 0 cx 1824 cy 988
rdpClientConProcessMsgClientInfo:
  got client info bytes 7072
  jpeg support 0
  offscreen support 0
  offscreen size 0
  offscreen entries 0
  client supports glyph cache but server disabled
  client can not do offscreen to offscreen blits
  client can do new(color) cursor
  client can not do multimon
rdpRRSetRdpOutputs: numCrtcs 1 numOutputs 1 monitorCount 0
rdpRRSetRdpOutputs: update output 0 left 0 top 0 width 1824 height 988
rdpRRUpdateOutput:
rdpLoadLayout: keylayout 0x00000409 variant  display 11
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat on
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
fuse: device not found, try 'modprobe fuse' first
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
rdpInDeferredRepeatCallback:
rdpkeybChangeKeyboardControl:
rdpkeybChangeKeyboardControl: autoRepeat off
guacd[617]: INFO:	Accepted format: 16-bit PCM with 2 channels at 44100 Hz
guacd[617]: INFO:	Accepted format: 16-bit PCM with 2 channels at 22050 Hz
guacd[617]: INFO:	Connected to RDPDR 1.12 as client 0x6484b1ca
guacd[617]: INFO:	RDPDR user logged on

**Comment by syndataDOTcom** [comment]
Issue remains on current build. Intrigued to understand why issue is closed without confirmation of resolution. Closing issues reported without remediating them brings the entire Digikam solution and integrity of code into question.

**Comment by syndataDOTcom** [comment]
Comment deleted

**Comment by nathabonfim59** [comment]
If anyone came across the same problem, a workaround is to run the container with the flag `--security-opt seccomp=unconfined`.
There are security implications, [more details here](https://gist.github.com/nathabonfim59/b088db8752673e1e7acace8806390242).

**Comment by andreascschmidt** [comment]
Thanks, that worked … I've read a few times and don't get the implications completely, but it's internal, and it works, so I'm good with that. 

Thanks a lot @nathabonfim59

**Comment by bombz88** [comment]
Hello, 
Seems after a recent update of the mysql docker and mysql workbench docker I have been receiving the following error with mysql workbench when accessing the web UI.

I have been unable to fix this. Any ideas?

![image](https://user-images.githubusercontent.com/63661554/203675950-6d53dbef-b8c6-40ea-93a9-691c89315ce6.png)

**Comment by bombz88** [comment]
> If anyone came across the same problem, a workaround is to run the container with the flag `--security-opt seccomp=unconfined`. There are security implications, [more details here](https://gist.github.com/nathabonfim59/b088db8752673e1e7acace8806390242).

I am not 100% clear on how to perform this container flag that is specified. Any clarification how to add this to a docker instance?
